### PR TITLE
Add a download link for `perovskites` export archive

### LINKED ISSUE #34: Add the `perovskites` export archive
The query builder part of the tutorial depends on some data being present in the database. The [old private tutorial repository](https://github.com/epfl-theos/tutorial-aiida-private/tree/master/export_archive) contained a folder with that archive. This had to be imported in the database and then the accompanying script had to be run to reinsert certain extras, since they could not be exported in the old AiiDA version. This archive should be migrated to the latest version and then recreated with the extras in place such that the script becomes obsolete. The archive should then be put in a public place with a permanent link that is put in the documentation text, such that users without the VM can still download, import and follow this part of the tutorial.

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #34 

The query builder part of the tutorial depends on some data being
present in the database. This data would be imported for the virtual
machine so it would be available to users during the tutorial. Importing
the archive was not enough, as it relied on some extras being set, which
at the time were not exportable. Therefore a script had to be run after
importing that would set these extras and recreated the groups for the
pseudo potential families. The archive was not made available publicly
which means that users running the tutorial in their own environment and
database could not perform this last section.

These problems have now been addressed:

 * The archive was migrated from v0.3 to v0.4 with `aiida-core==1.0.0b3`
 * The migrated archive was imported into a clean database
 * The pseudo potential family groups were recreated
 * The extras were set on the calculations and structure nodes:
   - Structure formula was set on the calculation node
   - `A` and `B` element of `ABO3` perovskite formule set on structure
 * The 3 pseudo family groups and 3 calculation groups were exported.
   - Only direct inputs and outputs of the calculations were included

The text in the query builder notebook has been updated to include a
link to this archive. For now this is a dropbox link, but should be
replaced with a permanent link once the archive is fully tested and
confirmed to be correct.

### CODE REVIEW

**Comment by sphuber** [comment]
@giovannipizzi I noticed a couple of inconsistencies between the tutorial text and the migration script that "fixed" the export archive:
* The scripts adds the extras `A` and `B` to the structures but the tutorial does not seem to reference them at all. Or I have missed it.
* The migration script *does not* add the `formula` extras to the structures even though the tutorial has the user filter the structures it and then says that it might not yet exist and then gives instructions on how to do it.
The archive also contained a bunch of other non-related nodes.
I have chosen to recreate all extras `A`, `B` and `formula` and only export those nodes strictly necessary for the perovskite example. The old script also set the users of some of the group to the default. I guess this will only work if you run the script in the same environment that then imports it. For now I have set it to a `aiida@localhost` dummy user.


The steps I followed to create the new archive on dropbox is the following:

 * Migrate old archive from v0.3 to v0.4 with current export migration branch
 * Import the migrated archive into a clean database
 * Executed the following script:
```
 #!/usr/bin/env runaiida
from aiida import orm
from aiida.orm.nodes.data.upf import UPFGROUP_TYPE

created, user = orm.User.objects.get_or_create(email='aiida@localhost')

if created:
    user.store()

for exx in ['pbe', 'pbesol', 'lda']:

    # Recreate the pseudo potential groups
    group_name = 'GBRV_{}'.format(exx)
    group, _ = orm.Group.objects.get_or_create(label=group_name, type_string=UPFGROUP_TYPE, user=user)
    group.user = user
    group.store()

    filters = {'attributes.filename': {'like': r'%\_{}\_%.UPF'.format(exx)}}
    builder = orm.QueryBuilder().append(orm.UpfData, filters=filters)
    group.add_nodes([entry[0] for entry in builder.all()])

    # Reinsert the extras: structure formula on the structure itself, and the perovskite components on the calculation
    group_name = 'tutorial_{}'.format(exx)
    group, _ = orm.Group.objects.get_or_create(label=group_name, user=user)
    group.user = user
    group.store()

    for calculation in group.nodes:
        structure = calculation.inputs.structure
        structure.set_extra('formula', structure.get_formula())
        calculation.set_extra('A', structure.sites[0].kind_name)
        calculation.set_extra('B', structure.sites[1].kind_name)
```
 * Created a new export archive with: `verdi export create -G 1 2 3 5 6 7 -f --no-create-reversed --no-return-reversed --no-call-reversed --no-input-forward -- tutorial_perovskites_migrated.aiida`

**Review by giovannipizzi — APPROVED** [review]
Ok for me - maybe could you open an issue to replace the link?

For the archive - all seems very good, let's see if all works (chapter + appendix) with this archive.
A few comments:

- it's possible A and B are not used, I think they were used for a previous version of the tutorial. Anyway good to keep them 
- good that you added the formula
- ok for the user (indeed the scripts were meant to prepare everything on the tutorial VM, now that the export file works better, it's ok to just have a "proper" export file)
- note that in day 1 we ask them to check some UUIDs - it would be good to double check that these nodes are still in the DB after importing, or to replace the nodes with equivalent nodes.

**Comment by sphuber** [comment]
For reference, after the migration steps detailed in the previous comment, I have performed some more steps to make the archive as if it would have been run with `aiida-core==1.0.0`.
After importing in a fresh database (so that the only thing it contains is the data of the archive), I did the following in the shell:
```
from aiida.engine import ProcessState

for [node] in QueryBuilder().append(ProcessNode).all():
    node.set_process_state(ProcessState.FINISHED)
    node.set_process_label('PwCalculation')
    node.set_exit_status(0)
```
This will ensure that `verdi process list` gives nice data and not all `None`.
Then I had to update the link labels of the pseudo inputs to `PwCalculation`.
The new `PwCalculation` specifies the input `pseudos` instead of `pseudo` and has been made a proper namespace. Inputs nested in namespaces, will have links where the namespaces are separated by 'double' underscores. This is to distinguish them from simple under scores in the name of the input port itself. This means that for example the old `pseudo_Si` would now become `pseudos__Si`. To fix this, I executed the following SQL:
```
UPDATE db_dblink SET label = regexp_replace(label, '^pseudo', 'pseudos_')
WHERE label LIKE 'pseudo\_%';
```
In addition, the old calculations still had the attribute `state` set to `FINISHED` which is no longer valid.
In `aiida-core==1.0.0` this attribute is deleted as soon as the calculation job terminates.
To make the data congruent I executed this SQL:
```
DELETE FROM db_dbattribute WHERE key = 'state';
```

The resulting data has been exported again to create a new updated archive availabel [here](https://drive.google.com/open?id=1BKqZbMt-yMuZqbFD33zjkqtt59f6IwDM)

**Comment by giovannipizzi** [comment]
Ok, so I guess this link name thing is something that is not being migrated (and will not be, since it's something related to a plugin and not to aiida_core)?

**Comment by sphuber** [comment]
Yes, exactly. Although the other points are about things internal to `aiida-core` and could/should be addressed for which I opened an issue today. The only problem is to figure out the exact behaviour because there is not a one-to-one mapping of old to new data, so we'll need your thoughts there as well

**Pull request merged**
