### PR TITLE
transifex integrated with travis CI into repository

### PR DESCRIPTION
**Pull request by unkcpz**
@ltalirz Same way as aiida-core's documentation localization.
The repository is held at https://github.com/unkcpz/aiida-tutorial-zh_CN now.
The traivis CI build successfully, https://travis-ci.org/unkcpz/aiida-tutorials/jobs/558791220 .

You can find output of readthedocs result here https://aiida-tutorial-zh-cn.readthedocs.io/zh_CN/latest/ .

### CODE REVIEW

**Comment by unkcpz** [comment]
And then you only need to:

- Setup password and user of transifex API, refer to  [integrating-the-client-with-travis-ci](https://docs.transifex.com/transifex-github-integration-point-click/github#integrating-the-client-with-travis-ci)
- modified `TRANSIFEX_PROJECT_NAME` in `.travis.yml`

**Comment by ltalirz** [comment]
Thanks @unkcpz, will do!

Two small questions:
 * Do you agree that we create the aiida-tutorials transifex project under the aiidateam organization ? https://www.transifex.com/aiidateam/public/
 * This is minor, but perhaps use `aiida-tutorials` instead of `aiida-tutorial`, just to be consistent with the name of the main repo

**Comment by unkcpz** [comment]
> Do you agree that we create the aiida-tutorials transifex project under the aiidateam organization ? https://www.transifex.com/aiidateam/public/

Yes. Where else could it be?

> This is minor, but perhaps use aiida-tutorials instead of aiida-tutorial, just to be consistent with the name of the main repo

Forgive me for my carelessness. It is fixed.  
https://aiida-tutorials-zh-cn.readthedocs.io/zh_CN/latest/
https://github.com/unkcpz/aiida-tutorials-zh_CN

**Review by ltalirz — APPROVED** [review]
thanks @unkcpz !

**Comment by ltalirz** [comment]
@unkcpz Everything seems to have worked fine - the files are available in transifex now

**Pull request merged**
