### PR TITLE
Include rest section

### PR DESCRIPTION
**Pull request by ltalirz**
I'm introducing the provenance browser as an alternative way of
browsing the provenance after ``verdi graph generate``.

I have tested that the basics work and the answers to the questions I pose are there but this section should also be tested by someone else.

For the moment I've kept the following explanations on how to use the
verdi cli to investigate the provenance graph.
Some if it may be redundant now.

### CODE REVIEW

**Comment by ltalirz** [comment]
@d-tomerini If you manage to find some time, could you perhaps test this new REST API section of the documentation and let me know whether it works?
You can take the latest VM from the google doc

The easiest would be to use the "command line instructions" at the bottom of the PR to pull the changes into your repo, and build the updated docs.

 * One caveat: In the link to the provenance explorer, replace www.materialscloud.org with dev-www.materialscloud.org (I believe @waychal has not yet updated the production server)

**Comment by d-tomerini** [comment]
Sure! I'll check it tomorrow morning and let you know

**Comment by waychal** [comment]
I haven't updated the production server yet. Let me know when its fine to update it.

**Comment by ltalirz** [comment]
@waychal The things I checked for the tutorial (connecting the aiida 1.0 rest api to dev-www) worked without further issues
You know best which changes you made - if there's something in particular that @d-tomerini should check, just let him know.

For moving to production, it would be good if you can have a look at some nodes of the existing explore sections to make sure they don't break. If that's fine, good to move to production!

**Comment by d-tomerini** [comment]
@ltalirz @waychal 

Normal exploration works for me. 

I had a problem with going to 'details' and entering a calculation node

> 'f you ever get lost, just go to the “Details” tab, enter ce81c420-7751-48f6-af8e-eb7c6a30cec3'

I get a warning

>  NODE is not supported!

that shows up any time I try to retrieve a calculation node (other types works fine). If I reach the node through exploration, I do not encounter this issue. I recovered the same behaviour in firefox, chrome, and brave

Some more context: I opened the VM -- 2.5, created a profile, downloaded the database, and started exploring it

**Comment by waychal** [comment]
@d-tomerini Thanks for finding the issue. I have fixed it and updated https://dev-www.materialscloud.org server.

**Comment by d-tomerini** [comment]
Thank you @waychal ! I re-tested it on the VM, and it works for me there now

**Comment by waychal** [comment]
Thanks @d-tomerini .
Today I will merge the changes in to staging branch and update the production server.

**Comment by ltalirz** [comment]
@sphuber Daniele has gone through the new stuff and it seems to work.
Would you also like to have another look before we merge this?

**Comment by sphuber** [comment]
Thanks to all

**Pull request merged**
