### PR TITLE
Fix aiida version and link to AiiDAlab cluster

### PR DESCRIPTION
**Pull request by mbercx**

### CODE REVIEW

**Review by giovannipizzi — APPROVED** [review]

**Review by csadorf — COMMENTED** [review]
The AiiDA version on aiidalab-demo is 1.4.3, but I guess it does not really matter.

**Comment by giovannipizzi** [comment]
Ah ok - maybe @mbercx you could fix this when you have time

**Comment by giovannipizzi** [comment]
Also, at variance with the VMs, the versions will change over time in the aiidalab-instances... so we need to be careful when we do major changes to AiiDAlab, to remember to go and update the tutorials unfortunately, otherwise tutorials might stop working

**Comment by mbercx** [comment]
> The AiiDA version on aiidalab-demo is 1.4.3, but I guess it does not really matter.

Whoops! Forgot to check the version on the aiidalab-demo cluster. Fixed in #309.

> Also, at variance with the VMs, the versions will change over time in the aiidalab-instances... so we need to be careful when we do major changes to AiiDAlab, to remember to go and update the tutorials unfortunately, otherwise tutorials might stop working

That's true. Maybe if all of the tutorial material is put into a Jupyter notebook format, it would be easy to test this automatically? Or at least it'd be easy just to run the (solution) notebook.

**Comment by chrisjsewell** [comment]
> to remember to go and update the tutorials unfortunately, otherwise tutorials might stop working

That does not make sense to me; tutorial documentation should be "frozen" once the tutorial has been given.
(a) it's a record what was actually presented on these days and (b) it would be unrealistic to have to update every tutorial, every time the aiidalab was updated

For the actual tutorial, it is obviously no problem to use the aiidalab-demonstrator. 
But for legacy use, we should only link to a fixed quantum mobile version.

**Comment by chrisjsewell** [comment]
> That's true. Maybe if all of the tutorial material is put into a Jupyter notebook format, it would be easy to test this automatically?

I've already raised a similar issue here https://github.com/marvel-nccr/ansible-role-aiida/issues/58

I intend to look into having a separate repository holding such jupyter notebooks, which would be tutorial independent, tagged per aiida release, and possibly tested using something like https://github.com/treebeardtech/treebeard or my own https://pytest-notebook.readthedocs.io/en/latest/

These notebooks would then automatically be copied into QM, dependant upon the aiida version it was built against, and could also be cherry picked for tutorials

**Comment by mbercx** [comment]
> That does not make sense to me; tutorial documentation should be "frozen" once the tutorial has been given.
> (a) it's a record what was actually presented on these days and (b) it would be unrealistic to have to update every tutorial, every time the aiidalab was updated

I think @giovannipizzi was referring to the "latest" tutorial material, for users that just want to learn AiiDA outside of the context of a tutorial event.

> But for legacy use, we should only link to a fixed quantum mobile version.

Yeah, I agree with that. That's also what I want to do with the BIGMAP tutorial now, once we move it into a `legacy` branch and keep just one version of the tutorial material on the `master` branch. (Or however we were planning to organise this)

**Comment by chrisjsewell** [comment]
I certainly still think that each tutorial should be a separate branch (#269)

But as we have discussed before, it is difficult to just have a "latest" tutorial, because all tutorials are slightly different; in their goals, available time, audience, etc.

This is where an aiida-notebooks repository would come in; it would just be a bunch of independent notebooks, not structured into any specific tutorial, each just focussing on a particular aspect of aiida or one of its plugins.
This would be easier to maintain per aiida release.

People downloading QM could then just use them at their leisure,
and for tutorials it would effectively be a one-to-many relationship, in that multiple tutorials could cherry pick notebooks based on their requirements.

**Comment by chrisjsewell** [comment]
FYI, Quantum Mobile is now also deployed as a Docker image: https://hub.docker.com/r/marvelnccr/quantum-mobile, which I think could be useful for testing the notebooks I talked about above

**Pull request merged**
