### PR TITLE
👌IMPROVE: Update the basics section

### PR DESCRIPTION
**Pull request by mbercx**

### CODE REVIEW

**Review by superstar54 — CHANGES_REQUESTED** [review]
There are several changes needed.
```
{code-block} console
Registered entry points for aiida.calculations:
(...)
* core.arithmetic.add
(...)
```

The output of this command needs update: 

```{code-block} console
$ verdi plugin list aiida.calculations arithmetic.add
```
Because there are only two required inputs now, please change the description after the output.

**Comment by mbercx** [comment]
Thanks @superstar54! Seems I missed some entry points indeed, these should be fixed now!

Regarding the code not being required, this is a consequence of a feature added to import completed `CalcJob`s in AiiDA. I've adapted the description, but it might be good to point to documentation describing this feature if there is any. @sphuber ?

**Comment by sphuber** [comment]
> Thanks @superstar54! Seems I missed some entry points indeed, these should be fixed now!
> 
> Regarding the code not being required, this is a consequence of a feature added to import completed `CalcJob`s in AiiDA. I've adapted the description, but it might be good to point to documentation describing this feature if there is any. @sphuber ?

https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/plugin_codes.html#writing-importers-for-existing-computations

**Comment by mbercx** [comment]
Thanks @sphuber! I've added a link in the margin to these docs so beginning users immediately know this is an option. @superstar54 can you check if there is anything else to change and approve if not?

**Review by superstar54 — APPROVED** [review]
LGTM!

**Pull request merged**
