### PR TITLE
Add data section

### PR DESCRIPTION
**Pull request by yakutovicha**
I checked the query examples in the notebook - they work fine.
Fixed a link to the AiiDA documentation that was not working.

As soon as the into is there, the links to it should be fixed.

### CODE REVIEW

**Review by chrisjsewell — CHANGES_REQUESTED** [review]
cheers @yakutovicha, and I'll look at the notebooks later

**Comment by chrisjsewell** [comment]
you know we are meeting now @yakutovicha!

**Comment by yakutovicha** [comment]
> you know we are meeting now @yakutovicha!

Thanks, please let me in.

**Comment by yakutovicha** [comment]
@chrisjsewell I put back the `querybuilder-template.ipynb` notebook as discussed yesterday. Please review

**Review by chrisjsewell — APPROVED** [review]
thanks @yakutovicha I can going to merge this as is, then make some changes in a 2nd PR (you'll see why later 👀)

**Pull request merged**
