### PR TITLE
Add page on exporting data

### PR DESCRIPTION
**Pull request by chrisjsewell**
adapted from https://gist.github.com/CasperWA/b0eacbf13b327aa25f97a5054ca8aced

### CODE REVIEW

**Comment by chrisjsewell** [comment]
see https://aiida-tutorials--271.org.readthedocs.build/en/271/pages/2020_Intro_Week/sections/retrieve_data.html

**Review by CasperWA — APPROVED** [review]
Approved on the condition that I'm credited with my work, i.e. that I get commit authorship :) Thanks.

**Comment by chrisjsewell** [comment]
> Approved on the condition that I'm credited with my work, i.e. that I get commit authorship :) Thanks.

well I did pretty much have to change every line 😜

**Comment by chrisjsewell** [comment]
@CasperWA make a change suggestion, so it adds you as co-author

**Comment by CasperWA** [comment]
> > Approved on the condition that I'm credited with my work, i.e. that I get commit authorship :) Thanks.
> 
> well I did pretty much have to change every line 😜

I should hope not. I wrote the file as markdown. It seems like the exact same file, with the addition of an "important" section?
Honestly, I would appreciate being acknowledged properly for this work - even though it is small it's still the major part on this PR. Essentially, I don't think it's right that _I_ am co-authoring.

**Comment by chrisjsewell** [comment]
> > > Approved on the condition that I'm credited with my work, i.e. that I get commit authorship :) Thanks.
> > 
> > 
> > well I did pretty much have to change every line 😜
> 
> I should hope not. I wrote the file as markdown. It seems like the exact same file, with the addition of an "important" section?
> Honestly, I would appreciate being acknowledged properly for this work - even though it is small it's still the major part on this PR. Essentially, I don't think it's right that _I_ am co-authoring.

ok will you'll have to make the PR yourself then, I have no idea how to make you author

**Comment by CasperWA** [comment]
> > > > Approved on the condition that I'm credited with my work, i.e. that I get commit authorship :) Thanks.
> > > 
> > > 
> > > well I did pretty much have to change every line 😜
> > 
> > 
> > I should hope not. I wrote the file as markdown. It seems like the exact same file, with the addition of an "important" section?
> > Honestly, I would appreciate being acknowledged properly for this work - even though it is small it's still the major part on this PR. Essentially, I don't think it's right that _I_ am co-authoring.
> 
> ok will you'll have to make the PR yourself then, I have no idea how to make you author

`git commit --amend --author "NAME <EMAIL>"`

**Pull request closed without merging**
