### PR TITLE
update instructions for workchains

### LINKED ISSUE #110: Make more explicit that WorkChain defintion needs to be in separate file
I think this should be mentioned in the tutorial, but maybe not clear enough. Any WorkChain defintion needs to be in a separate file from the script launching it. Otherwise you get `ImportError` `__main__.EquationOfState` not found

### LINKED ISSUE #111: Add instructions to add work chain implementations to python path
Related to #110 but this gets even worse if you submit to the daemon. In that case the module with work chain definitions needs to be in the python path. Since this needs to be in the path of the daemon workers, the path should be added to the python path in the activation script or otherwise the daemon worker won't pick it up

### PR DESCRIPTION
**Pull request by ltalirz**
closes #110 
closes #111 

 * mention that workchains need to be defined in separate files
 * add instructions on how to add a directory to the pythonpath

### CODE REVIEW

**Comment by ltalirz** [comment]
@sphuber Does this look sensible/sufficient?

For reference, the old instructions are here:
https://aiida-tutorials.readthedocs.io/en/xiamen2019/pages/2019_Xiamen/sections/workflows.html#workchains-or-how-not-to-get-lost-if-your-computer-shuts-down-or-crashes

**Comment by sphuber** [comment]
I think it looks fine but assuming there is someone with very little python experience:
* In addition to saying workchains need to be defined in a separate file, maybe also state explicitly how to then import the workchain in the running script
* Will adding `/home/max` to the python path make all python files available, no matter how deeply nested within that directory? Might be clearer to give a really explicit example. Say make folder `/home/max/workchains` and add that folder to python path. Then any python file in that folder, i.e. `/home/max/workchains/some_workchain.py` will be importable. In a running script in the same folder, e.g. `/home/max/workchains/run.py`, you can import your workchain like `from some_workchain import SomeWorkChain`.

**Comment by ltalirz** [comment]
thanks for the suggestions @sphuber - looking better now?

**Comment by sphuber** [comment]
> thanks for the suggestions @sphuber - looking better now?

You would think so, but I have been suprised by less in the past  :sweat_smile:

**Review by sphuber — APPROVED** [review]

**Pull request merged**
