### PR TITLE
Add cheat sheet material to repository

### PR DESCRIPTION
**Pull request by CasperWA**
Add cheat sheet to repository.

Updated cheat sheet from v18.05 (using a previous version of AiiDA prior to provenance redesign).

**Still to be done**:
- [x] Update version number (to v19.05).
- [x] Move cheat sheet folder into sub-folder of the latest tutorial.
- [x] Update link to AiiDA docs to refer to the latest version.
- [x] Add mention of AiiDA version this cheat sheet applies to (v1.0.0b3).

### CODE REVIEW

**Comment by CasperWA** [comment]
**Suggestion**:
Put "Useful links" in a box using the style of the box "Naming conventions" in order to distinguish it from the other boxes around it.

**Comment by ltalirz** [comment]
@CasperWA Thanks a lot for the update. I have a few suggestions

 - [x] should we add "Dict" as an example of a data node?
 - [x] Are "Float", "Int" etc. also data nodes? In any case, we should mention somewhere in the cheatsheet where you can get them from
 - [x] The factories: Instead of having this rather lengthy "if you would like to do..." what about simply adding a number of full examples, e.g. `ArrayData = DataFactory('array')` - first some for Data and then some for calculations (people are clever enough to "see the pattern")
 - [ ] fonts: are they actually all used? could we add just the ones we need (if they are used at all?)
 - [x] tutorial link: we'll merge into master, so you can just use `aiida-tutorials.readthedocs.org` (also for the docs link no need to add the `https://`, browsers will figure this out)
 - [x] verdi cli text suggestion:
   This list shows just the most common commands. Use TAB auto-completion at any level for a full list.

I let @sphuber checks the listed commands (or did you already check whether they exist?)

**Comment by ltalirz** [comment]
> Suggestion: Put "Useful links" in a box using the style of the box "Naming conventions" in order to distinguish it from the other boxes around it.

I think it looks fine as it is

**Comment by sphuber** [comment]
I'll mark some issues here with the cheatsheet:
Front:
- [x] `Code` is a sub class of `Data` but the tree doesn't represent this
- [x] Technically, `ProcessNode` should precede `CalculationNode` and `WorkflowNode`
- [x] `Node.get_incoming` says takes `<t>` type, which I imagine refers to node type, but it also takes link type and link label filters.
- [x] In typical usage, a user never needs `store_all` as this was used for storing calculations which is now always done by the engine. Maybe we should remove it.
- [x] The text for all the `Node` items does not really align with the command on the same line
- [x] For `Code`, remove `get_from_string` and promote usage of `load_code` instead
- [x] For `CalcJobNode` replace `get_state` with `process_state` and `exit_status` properties. Also add `is_finished` and `is_failed`.

Back:
- [x] Replace extra formula `Sn2O3` with `BaO3Ti` because the former does not exist
- [x] image bottom right uses `with_incomin` it is missing the letter `g` it seems.

Thanks a lot @CasperWA

**Comment by CasperWA** [comment]
@ltalirz

>     * should we add "Dict" as an example of a data node?

This existed already as "ParameterData" in the subclasses tree, however, I removed it to make it more "beautiful", since all other subclasses end with ...Data. But I can surely add it back in.

>     * Are "Float", "Int" etc. also data nodes? In any case, we should mention somewhere in the cheatsheet where you can get them from

They are, yes. Everything you need should be importable from `aiida.orm` in any case. Maybe we should add this sentiment/sentence somewhere?

**Edit**: Added a single "Dict, Float, Int, ..." to the figure. The stated question still stands.

>     * The factories: Instead of having this rather lengthy "if you would like to do..." what about simply adding a number of full examples, e.g. `ArrayData = DataFactory('array')` - first some for Data and then some for calculations (people are clever enough to "see the pattern")

Sure - just updated the existing text to the newest version, but maybe this is better?

>     * fonts: are they actually all used? could we add just the ones we need (if they are used at all?)

I can try and go through the document to see which fonts are used, but this will have a low priority.

> I let @sphuber checks the listed commands (or did you already check whether they exist?)

I already checked whether they exist and updated them all, however from @sphuber's marked issues above I will update them further.

**Comment by CasperWA** [comment]
@sphuber 

> Front:
>     * Technically, `ProcessNode` should precede `CalculationNode` and `WorkflowNode`

Is it important for a cheat sheet, or is it a thing you want to add for our own future understanding as well?

**Edit**: I have added it.

>     * `Node.get_incoming` says takes `<t>` type, which I imagine refers to node type, but it also takes link type and link label filters.

Sure, however, this will not fit in a nice way, I think?

>     * The text for all the `Node` items does not really align with the command on the same line

I don't see this - this may be a mistake of the conversion to pdf?

> Back:
>     * image bottom right uses `with_incomin` it is missing the letter `g` it seems.

Same as the comment above.

**Comment by sphuber** [comment]
I have ticked the two issues related to the font. I opened the SVG but probably because I did not have the correct fonts installed it was warped, so consider those fixed. With regards to the `get_incoming` I would then maybe remove the `<t>` completely

**Comment by CasperWA** [comment]
@sphuber, concerning "The Factories" and the rewriting asked for by @ltalirz, I realized that the case for the `CalculationFactory()` is not relevant anymore, I guess?
Now, it is recommended to go through the builder, correct? So the `CalculationFactory()` is only used to get - what; a `PwCalculation` class that _must_ instantiate new objects by also supplying a pre-made `options` dict, or?

**Comment by sphuber** [comment]
Not quite. The "standard" way of launching any process is through a launcher function, like `run` or `submit`. It takes as a first argument the process class and then the inputs as kwargs. So to launch a pw.x calculation you need the process class, which is `PwCalculation` which you can get with the factory. Alternatively you can instantiate a builder for the process class and simply pass that to the launcher function, e.g. `run` or `submit`. The builder you can get from *either* the process class or a `Code` instance.

**Comment by CasperWA** [comment]
All right @sphuber and @ltalirz, I have updated the pdf and svg files and tried to apply all your suggestions and comments.
The only thing missing is to remove non-used fonts to reduce the size of the repository and not pollute too much.

**Comment by ltalirz** [comment]
Hi @CasperWA, thanks for your work!

Some of the text on the first page under "the main AiiDA node subclasses" and "the factories" is not correct (e.g. CalculationFactories actually return CalcJob subclasses).
The underlying issue is that, while we are showing the Node hierarchy, the process hierarchy is missing (@CasperWA It is a copy of the hierarchy under `ProcessNode`, just without the `Node` suffix). 

For the tree: in terms of layout, I would propose:
```
 Node => Data => ...
      => ProcessNode => ...

      Process => ...
```
This could fill the whole left side under the title "AiiDA class hierarchy".

On the right, we could then add explaining text concerning imports etc.

suggestion for the text (to improve):
```
import aiida-core Node classes from aiida.orm using their class name

from aiida.orm import KpointsData
from aiida.orm import CalculationNode
from aiida.orm import Dict

import any Data class via the DataFactory using their <label> string

ArrayData = DataFactory('array')
KpointsData = DataFactory('array.kpoints')
Dict = DataFactory('dict')
MyData = DataFactory('plugin.my')

import any Process class via the CalculationFactory using their <label> string

PwCalculation = CalculationFactory("quantumespresso.pw")
VaspCalculation = CalculationFactory("vasp.scf")
```

minor:
 - [x] in the corner replace `AiiDA v1.0.0b3` with `aiida-core v1.0.0b3`  (we aren't using the aiida metapackage at the moment)


@sphuber I notice there is also no complete figure on this on the docs, i.e. [here](https://aiida-core.readthedocs.io/en/latest/concepts/provenance.html) we have one of the ProcessNode hierarchy but we are missing the figure that shows both hierarchies side-by-side.

**Comment by sphuber** [comment]
@ltalirz that is because there is no direct perfect analogue process hierarchy. There is of course the `WorkChain` and the `CalcJob`, but the corresponding process class for the `CalcFunctionNode` and `WorkFunctionNode` is `FunctionProcess`. This class is generated dynamically by the engine for both `calcfunctions` and `workfunctions`. Since the user never interacts with it or even *sees* it, I have not yet described it.

**Comment by ltalirz** [comment]
@sphuber Ok, so I gather you would suggest not to show it here.
Concerning the text on the right, does my suggestion look reasonable?

**Comment by sphuber** [comment]
> @sphuber Ok, so I gather you would suggest not to show it here.
> Concerning the text on the right, does my suggestion look reasonable?

I am not sure. I can see why the parallel with the node tree might be useful, but at the same time, I worry that the imperfect parallel regarding the `FunctionProcess` might confuse people.

Regarding the right side, a few minor remarks:
* You say to import `aiida-core` classes directly and include `Dict` and then say to use the factory for it as well. Since `Dict` is and will remain a built-in I would simply replace its example in the second part with `StructureData`.
* You say "import any `Process` class via ..." but this is only correct for `CalcJob` implementations. For `WorkChains` they should use the `WorkflowFactory`.

**Comment by CasperWA** [comment]
> > @sphuber Ok, so I gather you would suggest not to show it here.
> > Concerning the text on the right, does my suggestion look reasonable?
> 
> I am not sure. I can see why the parallel with the node tree might be useful, but at the same time, I worry that the imperfect parallel regarding the `FunctionProcess` might confuse people.

Great, I'll leave it out of the cheat sheet.

>     * You say "import any `Process` class via ..." but this is only correct for `CalcJob` implementations. For `WorkChains` they should use the `WorkflowFactory`.

Do you guys have any "standard" `WorkChain`s I can reference here?
I think one would be enough - the pattern should be clear by now. Otherwise I can simply mention the `WorkflowFactory`.
Do we have more Factories?

**Comment by CasperWA** [comment]
Updated the box, concerning factories/imports and the package name of the AiiDA version.
I have _not_ added examples for `WorkflowFactory`, and would like to rewrite/revisit the box again with some better text. Perhaps just a list of the available factories and two examples total (one for `DataFactory` and one for `CalculationFactory`?

**Comment by sphuber** [comment]
I think it is fine to be honest. Like you said, I think the pattern should be clear like this. We don't need an explicit work chain example I would say.

**Comment by ltalirz** [comment]
@sphuber feel free to merge once you're happy with the cheat sheet

**Pull request merged**
