### PR TITLE
Closes #28 update Si graph

### LINKED ISSUE #28: update si graph
@odarbelaeze I believe you updated the graph.svg, right?
This graph is used in a different section as well and there it also needs an "input only" version of the figure.
Could you please prepare it and then remove the "batio3" subfolder in sections/include/images/verdi_graph ?

### PR DESCRIPTION
**Pull request by odarbelaeze**
Now it looks different.

Here's the input only:

graph-input

And here's the complete graph

graph-full

### CODE REVIEW

**Comment by odarbelaeze** [comment]
@ltalirz how about this:

graph-full

**Comment by ltalirz** [comment]
Thanks, can you please check whether the old version of the graph is still needed in the 2019 folder?
https://github.com/aiidateam/aiida-tutorials/tree/fix-28-update-si-graph/docs/pages/2019_MARVEL_Psik_MaX/sections/include/images/verdi_graph

It is used in another place in the tutorial - just need to figure out whether the Si graph makes sense there (if yes, you can replace the link, otherwise you might need a batio3 verison)

**Comment by odarbelaeze** [comment]
Updating the `BaTiO` version for section 2.

**Comment by odarbelaeze** [comment]
So now, section 2 contains the BaTiO graph (full and input only):

graph-full

And section 4 contains the Si graph (full, but the input only is also available):

graph-full

**Review by ltalirz — APPROVED** [review]
thanks @odarbelaeze !

**Pull request merged**
