### PR TITLE
Update link to homepage for Oslo tutorial

### PR DESCRIPTION
**Pull request by espenfl**
Updated link to homepage for tutorial.

### CODE REVIEW

**Comment by espenfl** [comment]
Looks like the package setup needs some updates.

**Comment by mbercx** [comment]
Hi @espenfl! Yes, I also noticed this when preparing the material for our tutorial today in the `tutorial-2021-abc` branch. Here's the commit that fixes the latexpdf build: https://github.com/aiidateam/aiida-tutorials/pull/312/commits/767c289504430e2a0f7e925504bb4df92d1b680a

Could you quickly update this in this PR?

**Comment by espenfl** [comment]
> Hi @espenfl! Yes, I also noticed this when preparing the material for our tutorial today in the `tutorial-2021-abc` branch. Here's the commit that fixes the latexpdf build: [767c289](https://github.com/aiidateam/aiida-tutorials/commit/767c289504430e2a0f7e925504bb4df92d1b680a)
> 
> Could you quickly update this in this PR?

Done. Thanks.

**Comment by mbercx** [comment]
Thanks @espenfl!

**Pull request merged**
