### PR TITLE
Update 'Running processes' section for aiida 2.0

### PR DESCRIPTION
**Pull request by ramirezfranciscof**

### CODE REVIEW

**Review by chrisjsewell — CHANGES_REQUESTED** [review]
Thanks, I see though `wget [https://aiida-tutorials.readthedocs.io/en/tutorial-2021-intro](https://aiida-tutorials.readthedocs.io/en/tutorial-2021-intro/_downloads/ea4486c5b943d172e522da9bc9dc56ae/Si.pbe-n-rrkjus_psl.1.0.0.UPF)`, which should be changed to the correct branch

**Comment by ramirezfranciscof** [comment]
Ah, I understood we were doing all the 2.0 updates first and then any actual content, but I can do that now if you prefer.

The only issue is that there is no `tutorial-2022-intro` deployed right now (see [here](https://aiida-tutorials.readthedocs.io/en/tutorial-2022-intro/)) so that link is just going to be broken...

**Comment by ramirezfranciscof** [comment]
> Thanks, I see though `wget [https://aiida-tutorials.readthedocs.io/en/tutorial-2021-intro](https://aiida-tutorials.readthedocs.io/en/tutorial-2021-intro/_downloads/ea4486c5b943d172e522da9bc9dc56ae/Si.pbe-n-rrkjus_psl.1.0.0.UPF)`, which should be changed to the correct branch

On second thought @chrisjsewell I'm not exactly sure what to do here, because from what I could understand that link was not only added after the website was deployed, but it seems to have been generated at deploy time too (the `_downloads/<HASH>`), so I can't really anticipate what the final link will look like right?

**Comment by chrisjsewell** [comment]
He i think it would be better to just use the sphinx `download` role

**Comment by ramirezfranciscof** [comment]
You mean [this](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-download)? Right, I think this is what we do for the downloadable links embedded in the text, but I don't see that having the option to explicitly write the weblink address, does it? (I remember searching during the last tutorial but couldn't find anything)

**Comment by mbercx** [comment]
Merging this as is, have opened issue regarding the `wget` code snippets:

https://github.com/aiidateam/aiida-tutorials/issues/430

**Pull request merged**
