### PR TITLE
Improve "Working with data" section

### PR DESCRIPTION
**Pull request by chrisjsewell**
This PR introduces two things:

1. Moving from `recommonmark`+`nbsphinx` to `myst-nb`.
2. Adding a binder environment and link in the documentation

The outcome of this is encapsulated in [querybuilder-template.md](https://github.com/aiidateam/aiida-tutorials/blob/myst-nb2/docs/pages/2020_Intro_Week/notebooks/querybuilder-template.md) and [querybuilder-tutorial.html](https://aiida-tutorials.readthedocs.io/en/myst-nb2/pages/2020_Intro_Week/notebooks/querybuilder-tutorial.html).
The notebooks can be written as plain markdown files, which are automagically converted (by jupytext) to notebooks when opened in Jupyter. This make them a lot easier to read and review.

All markdown files also allow for additional (MyST) syntax which incorporates (nearly) all reStructuredText features (roles, directives, etc).

Some notes on how I generated the Binder Docker environment, are in `binder/README.md`.
I first tried to use a simple `environment.yaml`, but there were some insurmountable version clashes, so I created a custom Docker image ([see binder docs](https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html)), by adapting the default Dockerfile created by [repo2docker](https://github.com/jupyter/repo2docker).

### CODE REVIEW

**Review by csadorf — COMMENTED** [review]
@chrisjsewell For the review, should I open this directly in mybinder and what exactly should I be looking for? Proper formatting/layout or also content?

**Comment by chrisjsewell** [comment]
> @chrisjsewell For the review, should I open this directly in mybinder and what exactly should I be looking for? Proper formatting/layout or also content?

Ermm all of the above lol. But yes, I guess as a first parse:

1. Do you see any issues with the pages converted from markdown/notebooks in: https://aiida-tutorials.readthedocs.io/en/myst-nb2 (and comparing to https://aiida-tutorials.readthedocs.io/en/2020-intro-week)
2. Can you open mybinder from the link at the top of https://aiida-tutorials.readthedocs.io/en/myst-nb2/pages/2020_Intro_Week/notebooks/querybuilder-tutorial.html; does it start the notebook correctly (and timely), and can you run through the notebook:
   - Note, I have made the link to the "tutorial" version of the notebook, so it won't run through fully without modifying some cells
   - I could also link to the "solutions" version, or just have the link open the notebook folder?
3. Have a look at the actual `binder/` folder: does the way I am creating the environment seem reasonable?
   - note it is created with aiida-core version 1.2.1 for now, since this is the latest version available from conda, but actually for the 2020 tutorial we are using 1.3.0.
   - to populate the initial database, I import `docs/pages/2020_Intro_Week/notebooks/tutorial_perovskites_v0.1.aiida`. This and the aiida-core version obviously make the environment specific to the 2020 tutorial. I don't see how you could really have specific environments for each tutorial, in the repo's current format (perhaps it would be better to have each tutorial as a separate branch, but thats not something for this PR)

**Comment by csadorf** [comment]
@chrisjsewell Is this time critical? I might not be able to get to this anymore today.

**Comment by chrisjsewell** [comment]
> @chrisjsewell Is this time critical? I might not be able to get to this anymore today.

thats ok, when might you be able to have a quick check?

**Comment by csadorf** [comment]
> > @chrisjsewell Is this time critical? I might not be able to get to this anymore today.
> 
> thats ok, when might you be able to have a quick check?

Sometime next week, however I will need to do it in between attending SciPy.

**Comment by chrisjsewell** [comment]
Ok I've removed the Binder for now, and will add later in a separate PR. 
Still got some work to do on it but I'm heading out now so won't be working on it until later
@mbercx this adds in (and expands on) the group appendix, and also I'll try to add in the provenance browser appendix.

**Comment by chrisjsewell** [comment]
rebased to #253

**Pull request closed without merging**
