### PR TITLE
Dependencies: update `Sphinx` and `jinja2` for compability

### PR DESCRIPTION
**Pull request by sphuber**
Jinja2 recently removed some resources that were still being used by
Sphinx 3. Upgrading both solves the issue. `myst-nb` also needed to be
upgraded to get compatibility with latest `Sphinx`.

### CODE REVIEW

**Review by chrisjsewell — CHANGES_REQUESTED** [review]
Cheers, as the warning messages say in https://readthedocs.org/projects/aiida-tutorials/builds/17923068/, some configuration variable names need to be changed in conf.py

**Comment by chrisjsewell** [comment]
> upgraded to get compatibility with latest Sphinx.

Note sphinx v5 is actually the latest, but sphinx-book-theme is still pinned to v4 (myst-nb is compatible)

**Comment by chrisjsewell** [comment]
So change `jupyter_execute_notebooks` to `nb_execution_mode`, and maybe just delete the `nb_render_priority` variable, since that has changed completely in format and may no longer be necessary.

Plus, at the top of https://github.com/aiidateam/aiida-tutorials/blob/tutorial-2022-intro/docs/sections/running_processes/workflows.md, change

```
---
substitutions:
  seekpath: "[SeeK-path](https://www.materialscloud.org/work/tools/seekpath)"
---
```

to

```
---
myst:
  substitutions:
    seekpath: "[SeeK-path](https://www.materialscloud.org/work/tools/seekpath)"
---
```

**Comment by sphuber** [comment]
@chrisjsewell addressed the warnings for newer `myst-nb` but the build is still failing as mentioned in the slack thread. You know how to fix it?

**Comment by chrisjsewell** [comment]
for the pre-commit, just change https://github.com/aiidateam/aiida-tutorials/blob/485a9dd366fff418a1a4c2be7c19cf86060e2f8b/.pre-commit-config.yaml#L21-L26,
so that `rev` points towards `v6.1.0` (latest on https://github.com/rstcheck/rstcheck), and I guess also update the sphinx version dependency

**Comment by sphuber** [comment]
> for the pre-commit, just change
> 
> https://github.com/aiidateam/aiida-tutorials/blob/485a9dd366fff418a1a4c2be7c19cf86060e2f8b/.pre-commit-config.yaml#L21-L26
> ,
> so that `rev` points towards `v6.1.0` (latest on https://github.com/rstcheck/rstcheck), and I guess also update the sphinx version dependency

Yeah, just did that. Ah, missed the sphinx reference though. Will update that now

**Comment by chrisjsewell** [comment]
and yeh the linking is due to https://github.com/aiidateam/aiida-core/issues/5518, I'll have a look/think today, if there is a decent fix

**Comment by chrisjsewell** [comment]
For the two issues with intersphinx:

```
/home/runner/work/aiida-tutorials/aiida-tutorials/docs/sections/writing_workflows/errors.md:34: WARNING: py:meth reference target not found: aiida.orm.nodes.process.ProcessNode.is_failed
/home/runner/work/aiida-tutorials/aiida-tutorials/docs/sections/writing_workflows/errors.md:427: WARNING: py:meth reference target not found: aiida.orm.nodes.process.process.ProcessNode.exit_status
```

I downloaded https://aiida.readthedocs.io/projects/aiida-core/en/latest/objects.inv, then used https://github.com/bskinn/sphobjinv to inspect.

Its actually the case that now both are not `py:meth` but `py:property`:

`` :py:property:`aiida.orm.nodes.process.process.ProcessNode.is_failed` ``, `` :py:property:`aiida.orm.nodes.process.process.ProcessNode.exit_status` ``

**Comment by chrisjsewell** [comment]
oh and one more, change `git://github.com/pre-commit/pre-commit-hooks` in the pre-commit config to `https://github.com/pre-commit/pre-commit-hooks`

**Review by chrisjsewell — APPROVED** [review]
lokks good cheers

**Pull request merged**
