### PR TITLE
Fix workflow section and appendix

### PR DESCRIPTION
**Pull request by sphuber**

### CODE REVIEW

**Comment by ltalirz** [comment]
@sphuber Thanks! I noticed there are a few .pyc files in there, which I guess are not there intentionally.
Once these are removed I would already merge the PR; we can then iterate on top

**Comment by ltalirz** [comment]
One more question: I see there are `scripts/` and `sections/include` (snippets/images).

What if you want to show part of a script but also offer it for download (e.g. that would be the case for the jupyter notebooks)?
Is there really a reason to differentiate between scripts and snippets in different levels of the folder hierarchy?

What about a structure
```
pages/2019_MARVEL_Psik_MaX/
  index.rst
  sections/
  images/
  code/
``` 
That makes it easy lateron to find what code & images were used in the tutorial.

In `code` one could then still decide to differentiate files into different folders or not, depending what is convenient.

**Comment by sphuber** [comment]
The reason for the separation is that the `scripts` are supposed to be completed working examples. I put them on the same level as the `notebooks` directory. The snippets however are literally just that, some snippets that are not necessarily complete and cannot be expected to be runnable. Now this does force some code duplication which is annoying as it runs the risk of the scripts and snippets getting out of sync. However, I am not sure if it is possible to include an excerpt of a file in .rst If this were the case we could just have the script and then use line numbers to select certain snippets to show in the text. However, that would still not solve everything as sometimes in the text we deliberately show incomplete or wrong code for illustration purposes. Having these snippets among 'working' scripts may become confusing.

**Comment by ltalirz** [comment]
> However, I am not sure if it is possible to include an excerpt of a file in .rst

That should be possible, see https://www.sphinx-doc.org/en/1.5/markup/code.html#includes

> sometimes in the text we deliberately show incomplete or wrong code for illustration purposes.

In this case, since they aren't executable anyhow, you might also just include them in the .rst file directly. Up to you.

**Comment by sphuber** [comment]
@ltalirz this is good to go so others can work off it

**Comment by ltalirz** [comment]
thanks @sphuber !

**Pull request merged**
