### PR TITLE
👌 IMPROVE: Calculation processes - Running external codes

### LINKED ISSUE #215: 👌 IMPROVE: Use the `aiida-pseudo` package for installing pseudos
This would avoid to run these lines (see #214):
```bash
mkdir sssp_pseudos
wget 'https://archive.materialscloud.org/record/file?filename=SSSP_1.1_PBE_efficiency.tar.gz&record_id=23&file_id=d2ce4186-bf76-4e05-8b39-444b4da30273' -O SSSP_1.1_PBE_efficiency.tar.gz
tar -C sssp_pseudos -zxvf SSSP_1.1_PBE_efficiency.tar.gz
verdi data upf uploadfamily sssp_pseudos 'SSSP' 'SSSP pseudopotential library'
```
@sphuber is the package ready? What would be the equivalent commands? @chrisjsewell is it already in the quantum mobile?

### LINKED ISSUE #355: 👌 IMPROVE: "Running calculations - Basics" module
Continuing from the AiiDA Basics in the "Fundamentals" section, the first thing we want the participants to do is to run their own Quantum ESPRESSO calculation using AiiDA, so they can understand more about:

* How to import a structure
* How to set up a code
* How to install pseudopotentials
* How to set up inputs for a calculation
* How to analyse outputs of a calculation

This section will be largely based on the one used for the BIGMAP/ABC/QEschool tutorials, but could do with a quick revision.

### PR DESCRIPTION
**Pull request by ramirezfranciscof**
Somewhat "major" revamping of the ex [running computations](https://aiida-tutorials.readthedocs.io/en/latest/pages/2020_Intro_Week/sections/running.html) section.

The most important changes or focuses are:

- Removed all things related to troubleshooting (see #353 )
- Changed introduction to highlight the contrast between how data is organized when running normally vs running with AiiDA. This is in hope that it'll illustrate more explicitly "how to do with AiiDA the things I already know how to do on my own".
- Separated main content into 2 main sections: preliminary setups (which are performed using `verdi` CLI) and preparing the calculation (which is performed using the `verdi shell`). This is to address the problem we typically have of people needing to go back and forth from bash to python.

The two final sections (`Submitting the calculation` and `Exploring the results`) ended up rather short, I may re-juggle them a bit more? Or expand a bit on the final "exercises" on analyzing the outputs. Not entirely sure yet, but first I need to take a pass at the moved `running workflows` module (see #356 ) before getting back to this. Ideas are welcome for this.

I also wanted to maybe remove some of the commands. For example, we don't need to explicitly have the `builder.<port> = <node>` for every input, after the first or second ones maybe we can leave it to them to assign them (so that they have to think at least some small thing instead of just copy-pasteing everything). Again, I wanted to think a bit better how best to do this but I need to deal with the other module first.

closes #355 
closes #215

### CODE REVIEW

**Comment by ramirezfranciscof** [comment]
Just before everybody starts panicking, the 14k line modifications come from the fact that I added a pseudopotential file people can download (and a couple also from an SVG file I included).

**Comment by ramirezfranciscof** [comment]
I need to do some further modifications on this. Just letting you know if by any chance if any of you @mbercx @CasperWA is in the middle of reviewing this PR, maybe you could submit the partial comments you have so far and I'll ping you again once I'm done.

**Comment by mbercx** [comment]
> I need to do some further modifications on this. Just letting you know if by any chance if any of you @mbercx @CasperWA is in the middle of reviewing this PR, maybe you could submit the partial comments you have so far and I'll ping you again once I'm done.

Do you mind if I already merge the PR's that rename the "units" first? Might result in some merge conflicts, but nothing you can't handle. ;)

**Comment by ramirezfranciscof** [comment]
> Do you mind if I already merge the PR's that rename the "units" first? Might result in some merge conflicts, but nothing you can't handle. ;)

Yeah go ahead 👍🏽

**Comment by ramirezfranciscof** [comment]
I think the bulk of the module is complete now, I still need to think a bit about the exercises but perhaps I can finish that in the weekend.

Anyways, ready to review.

**Review by mbercx — APPROVED** [review]
I didn't do an in-depth review, but it looks like a vast improvement of the section, thanks a lot @ramirezfranciscof!

We can still do a pass later to hash out some details, but I'm merging this so I can send out the link to the participants.

**Pull request merged**
