### PR TITLE
Automating jupyter notebook generation

### PR DESCRIPTION
**Pull request by giovannipizzi**
The script to generate both versions (tutorials and
solutions) of the tutorial is integrated with the
Makefile. Moreover I put back in place the correct
version both for the 2018 and the 2019 tutorial.
This means that the jupyter notebook in aiida_demos
(in the branch tutorial_2019) will be now deleted and
the one provided here is the "official" version.

I now display the tutorial version of the notebook,
and I provide the solutions as a downloadable file.
Further changes can be done in this repository,
to the *-template.ipynb file.

### CODE REVIEW

**Comment by giovannipizzi** [comment]
@ltalirz Note that I put back in place the notebooks from the `aiida_demos` tutorial - I saw some minor changes to them in the git history of this repo - did you do any adaptation? In this case could you let me know, or could you please apply again on the `*-template.ipynb` files. Thanks!

**Comment by giovannipizzi** [comment]
@ltalirz ah, I see at least one thing that you fixed, the `-` sign in the jupyter notebooks that was some weird Unicode symbol and LaTeX didn't like. I fixed this, I don't know if there was more

**Comment by ltalirz** [comment]
Thanks a lot @giovannipizzi !

> This means that the jupyter notebook in aiida_demos (in the branch tutorial_2019) will be now deleted and the one provided here is the "official" version.

Thanks! I will check how to fix the aiida_demos build (for aiida 0.12) there and then merge your changes.

> I now display the tutorial version of the notebook, and I provide the solutions as a downloadable file.

That's great. I would propose to add a download of the "tutorial" one as well - this way people can follow the tutorial on different setups as well. Do you agree?

>  I fixed this, I don't know if there was more

Thanks, this was the only change I did.

**Comment by giovannipizzi** [comment]
> That's great. I would propose to add a download of the "tutorial" one as well - this way people can follow the tutorial on different setups as well. Do you agree?

Pushed a new commit with that (also fixed a wrong link)

**Review by ltalirz — APPROVED** [review]
thanks a lot @giovannipizzi

**Pull request merged**
